name       : perl-cairo-gobject
version    : '1.005'
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/X/XA/XAOC/Cairo-GObject-1.005.tar.gz : 8d896444d71e1d0bca3d24e31e5d82bd0d9542aaed91d1fb7eab367bce675c50
homepage   : https://metacpan.org/pod/Cairo::GObject
license    : LGPL-2.1-or-later
component  : programming.perl
summary    : Cairo::GObject - Integrate Cairo into the Glib type system
description: |
    Cairo::GObject registers Cairo's types (Cairo::Context, Cairo::Surface, etc.) with Glib's type systems so that they can be used normally in signals and properties.
builddeps  :
    - pkgconfig(cairo-gobject)
    - perl-cairo
    - perl-extutils-depends
    - perl-extutils-pkgconfig
    - perl-glib
rundeps    :
    - perl-cairo
    - perl-glib
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
